# Generated by Django 5.1.7 on 2025-04-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='chef',
        ),
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
