# Generated by Django 5.1.7 on 2025-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_food_restaurant_alter_chef_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
