# Generated by Django 5.1.7 on 2025-04-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_food_food_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
    ]
